### ISSUE TITLE
CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled 

### ISSUE THREAD

**Issue by brianread108** [wufoo/Wufoo-PHP-API-Wrapper#8]
Since yesterday I get this:

Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in /home/e-smith/files/ibays/mesdb/html/WufooApiWrapperBase.php on line 107

Fatal error: Uncaught exception 'WufooException' with message 'SSL connect error' in /home/e-smith/files/ibays/mesdb/html/WufooApiWrapperBase.php:118 Stack trace: #0 /home/e-smith/files/ibays/mesdb/html/WufooApiWrapperBase.php(42): WufooCurl->checkForCurlErrors() #1 /home/e-smith/files/ibays/mesdb/html/WufooApiWrapper.php(70): WufooCurl->getAuthenticated('https://goldend...', '**_obscured**_*') #2 /home/e-smith/files/ibays/mesdb/html/MESWufooLinks.php(38): WufooApiWrapper->getFields(11) #3 {main} thrown in /home/e-smith/files/ibays/mesdb/html/WufooApiWrapperBase.php on line 118

Looks like the CURL library or the PHP has changed?  this has been working for at least 18 months, and nothing has changed.

**Comment by brianread108** [comment]
I've now had this back from Wufoo support (and attach my response).  Looks like that are no longer interested in this integration, which is, I think. quite a shame.

**MY RESPONSE to them:**
Hi Michael

I am very disappointed that you are not prepared to continue providing a viable interface to your API for use in Php - the common most scripting language on the internet.

You may have noticed that there are a number of pull requests for updates to the package on the github account, one of which seems relevant, but when I tried it it did not cure the apparent problem.

Although I am a seasoned programmer (of 40 years!) I do not have the background to quickly see what the problem is. The program that I use computes links that we use in our MailChimp emails to allow our customers to access directly the Wufoo form with some of the relevant information filled in (name, emails address, and the chosen product).  This has proved very successful over the 2-3 years we have been using it, and has in large part kept us with Wufoo rather than going for a more integrated solution for booking online.  It is used by 3 separate offices in the country independently (for two separate course locations), in the preparation of  their emails.

I assume that your other integrations will also suffer from the same problems, I see that you python integration ("pyfoo") has not been updated also in the last 6 years, and also has a number of pull requests (and one issue) which have been ignored.

Jquery gives a 404 (page not found)

Java also not updated for 6 years.

Only the Ruby package is newer - 2 years ago is the latest.  Ruby is very popular, but not in the same league as php.

I suggest you should update your blog page:

https://www.wufoo.com/2012/03/21/so-you-want-to-integrate-with-wufoo/#dataapi

to say that you no longer support these languages else you will loose a lot of credibility if someone puts in effort to craft a program and then finds that the package you supply is flawed!!

I hope you'll pass my comments onto your product team.

I suspect that once I report  back to my superiors, they will encourage me to look elsewhere for this  type of facility, or indeed speed up  plans to integrate our online booking much more deeply with our web sites.

Cheers Brian
brianr@bjsystems.co.uk 

**THEIR RESPONSE to my Support request:**

**Comment by brianread108** [comment]
Ok, so I've cloned this repo to my own account:

https://github.com/brianread108/Wufoo-PHP-API-Wrapper

and applied the pull request that seems relevant from [here,](https://github.com/wufoo/Wufoo-PHP-API-Wrapper/pull/4) and the intial error message has gone away, however I am now getting an exception thrown which indicates "WufooException' with message 'SSL connect error' ".  Which I am relating to the Wufoo support saying that they have updated the SSL Certificates recently (in the last week) to eliminate the "broken" protocols, and that a Minimum of TLS1.1 is required.

I am working to try and force the connection onto a valid protocol, without a lot of success (I am bu no means an expert at this particular stuff!).

IO am posting this here incase others come across the problem, and would lie to help. I nwhich case, please wade in to my cloned repository:

https://github.com/brianread108/Wufoo-PHP-API-Wrapper

and hopefully we can fix this...

**Comment by brianread108** [comment]
Not having a lot of success with this - I def. need someone who understands these things a bit more than me!

https://github.com/brianread108/Wufoo-PHP-API-Wrapper
